fixed tagging and release permissions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -118,7 +118,7 @@ jobs:
       - name: Read version file
         id: get_tag
         run: |
-          echo "tag=$(cat VERSION)" >> "$GITHUB_OUTPUT"
+          echo "tag=$(cat VERSION)" >> $GITHUB_OUTPUT
 
       - name: Check if tag exists
         id: check_tag
@@ -127,22 +127,6 @@ jobs:
             echo "Tag v${{ steps.get_tag.outputs.tag }} already exists. Iterate tag version and reattempt"
             exit 1
           fi
-
-      - name: Create tag and push
-        env:
-          RELEASE_PAT: ${{ secrets.RELEASE_PAT }}
-        run: |
-          TAG="${{ steps.get_tag.outputs.tag }}"
-          if [ -z "$TAG" ]; then
-            echo "No tag present. failing and exiting"
-            exit 1
-          fi
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-
-          git remote -v 
-          git tag "v${TAG}"
-          git push origin "v${TAG}"
 
       # Download each artifact by name
       - name: Download Ubuntu artifact
@@ -176,8 +160,25 @@ jobs:
 
           files: |
             artifacts/kill-the-kings-ubuntu-latest/kill-the-kings
-            artifacts/kill-the-kings-macos-latest-arm64/kill-the-kings
-            artifacts/kill-the-kings-macos-latest-x86_64/kill-the-kings
+            artifacts/kill-the-kings-macos-latest-aarch64-apple-darwin/kill-the-kings
+            artifacts/kill-the-kings-macos-latest-x86_64-apple-darwin/kill-the-kings
             artifacts/kill-the-kings-windows-latest/kill-the-kings.exe
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # Tag ONLY once we know upload went smoothly
+      - name: Create tag and push
+        env:
+          RELEASE_PAT: ${{ secrets.RELEASE_PAT }}
+        run: |
+          TAG="${{ steps.get_tag.outputs.tag }}"
+          if [ -z "$TAG" ]; then
+            echo "No tag present. failing and exiting"
+            exit 1
+          fi
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+
+          git remote -v 
+          git tag "v${TAG}"
+          git push origin "v${TAG}"
